#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

# Create directory if it doesn't exist
mkdir -p /etc/nginx/sites-available/

# Write Nginx configuration file
tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart
