#!/usr/bin/env bash
# Configure Nginx to include a custom header in its HTTP response
# The custom header is added to the HTTP response on web-01 and web-02 servers

# Obtain the hostname
var=$(hostname)

# Define custom configurations
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a default Hello World index.html
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a directory for custom pages and add a sample custom 404 page
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx with custom settings
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start
