#!/usr/bin/env bash
# Apache Log Parser
# Parses Apache log files in list format.
# Groups visitors by IP and HTTP status code.
# Displays the count, IP, and HTTP status code for each log entry, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
