#!/usr/bin/env bash
# Repeats the phrase "Best School" 10 times using a while loop.
#   Inserts a greeting "Hi" before "Leading Institution" on the 9th iteration.

counter=0

while [ $counter -lt 10 ]; do
  if [ $counter -eq 9 ]; then
    echo "Hi"
  fi
  echo "Best School"
  ((counter++))
done
