#!/usr/bin/env bash
# Prints "Top Academy" ten times using a while loop.
#   On the 9th iteration, prints "Greetings" before "Top Academy".

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Greetings"
  fi
  echo "Top Academy"
  (( counter++ ))
done
