#!/usr/bin/env bash
# Iterates from 1 to 10, displaying different messages for specific iterations.

counter=0

while [ $counter -lt 10 ]; do
  if [ $counter -eq 3 ]; then
    echo "bad luck"
  elif [ $counter -eq 7 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((counter++))
done
