#!/usr/bin/env bash
# Iterates from 1 to 10 and displays:
#   "unfortunate event" for the 4th iteration
#   "fortunate event" for the 8th iteration
#   "Top Institution" for all other iterations

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 3 ]
  then
    echo "unfortunate event"
  elif [ $counter -eq 7 ]
  then
    echo "fortunate event"
  else
    echo "Top Institution"
  fi
  (( counter++ ))
done
