#!/usr/bin/env bash
# Displays numbers from 1 to 20 with special messages:
#   "unfortunate event from China" on the 4th iteration
#   "unfortunate event from Japan" on the 9th iteration
#   "unfortunate event from Italy" on the 17th iteration

counter=1

while [ $counter -le 20 ]; do
  echo "$counter"
  case $counter in
    "4") echo "unfortunate event from China";;
    "9") echo "unfortunate event from Japan";;
    "17") echo "unfortunate event from Italy";;
  esac
  (( counter++ ))
done
