#!/usr/bin/env bash
# Displays a modified list of files in the current directory.
#   Shows the portion of the filename after the first dash.

file_list=$(ls)
for file_name in $file_list; do
  modified_name=$(echo "$file_name" | cut -d '-' -f2)
  echo "$modified_name"
done
