#!/usr/bin/env bash
# Update localhost to 127.0.0.2 and facebook.com to 8.8.8.8 in the hosts file

# Create a copy of the hosts file
cp /etc/hosts ~/hosts.new

# Modify the copied hosts file to change localhost and facebook.com
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Overwrite the original hosts file with the updated version
cp -f ~/hosts.new /etc/hosts
