#!/usr/bin/env bash

# Stop any running apache2 processes
pkill -f apache2

# Change ownership and permissions of nginx.conf to be used by nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

# Change the default port from 80 to 8080 in the default Nginx configuration file
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# Start Nginx service running as the nginx user
sudo -u nginx service nginx start
