#!/usr/bin/env bash
# Stop any running apache2 processes and start nginx as the nginx user on port 8080
sudo -u nginx pkill apache2
sudo -u nginx chown 700 /etc/nginx/nginx.conf
sudo -u nginx sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
